# Generated by Django 4.0 on 2022-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_by_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
