# Generated by Django 4.0 on 2022-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_has_delete_perm_user_has_edit_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_po_user',
            field=models.BooleanField(default=False),
        ),
    ]
