# Generated by Django 4.0 on 2022-01-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visited', models.CharField(blank=True, max_length=100, null=True)),
                ('next_visit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('last_meeting_date', models.DateField(auto_now_add=True, null=True)),
                ('next_meeting_date', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
