# Generated by Django 4.0 on 2022-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanagement',
            name='tour_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourmanagement',
            name='tour_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
