# Generated by Django 4.0 on 2022-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tourmanagement_tour_from_tourmanagement_tour_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmanagement',
            name='last_meeting_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
