# Generated by Django 4.0 on 2022-01-16 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_user_join_date'),
        ('dashboard', '0003_alter_tourmanagement_last_meeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour_member_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='tourmanagement',
            name='member',
        ),
        migrations.AddField(
            model_name='tourmanagement',
            name='status',
            field=models.CharField(blank=True, choices=[('pending approval', 'pending approval'), ('approved', 'approved'), ('tour finished', 'tour finished')], default='pending approval', max_length=90),
        ),
        migrations.AddField(
            model_name='tourmanagement',
            name='tour_members',
            field=models.ManyToManyField(through='dashboard.tour_member_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour_member_data',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tourmanagement'),
        ),
    ]
