# Generated by Django 4.0 on 2022-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tour_member_data_remove_tourmanagement_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanagement',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
