# Generated by Django 4.0 on 2022-01-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_join_date'),
        ('dashboard', '0005_tourmanagement_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmanagement',
            name='status',
            field=models.CharField(blank=True, choices=[('pending approval', 'pending approval'), ('approved', 'approved'), ('finished', 'finished')], default='pending approval', max_length=90),
        ),
        migrations.CreateModel(
            name='tour_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/tour/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tourmanagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
