# Generated by Django 4.0 on 2022-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tourmanagement_status_tour_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanagement',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour_files',
            name='file',
            field=models.FileField(upload_to='tour/'),
        ),
    ]
