# Generated by Django 4.0 on 2022-01-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_tourmanagement_date_alter_tour_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanagement',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tourmanagement',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
