# Generated by Django 4.0 on 2022-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_tour_places_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_places',
            name='organization',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
