# Generated by Django 4.0 on 2022-01-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_tour_places_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300, null=True)),
                ('sector_name', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
