# Generated by Django 4.0 on 2022-02-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_sub_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmanagement',
            name='actual_visit_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourmanagement',
            name='report_submission_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
