# Generated by Django 4.0 on 2022-02-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement_plan_for_goods',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
