# Generated by Django 4.0 on 2022-02-20 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0003_procurement_plan_for_goods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement_plan_for_goods',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
