# Generated by Django 4.0 on 2022-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_sector', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('budget_head', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_budget_head1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('training_title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('training_topic', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('budget', models.FloatField(blank=True, default=0, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('batch', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('total_session_conducted', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_facilitator_official', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_facilitator_private', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_facilitator_internal', models.IntegerField(blank=True, default=0, null=True)),
                ('information_of_facilitator_official', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('information_of_facilitator_private', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('information_of_facilitator_internal', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('total_number_of_trainer', models.IntegerField(blank=True, default=0, null=True)),
                ('po_male_perticipent', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('po_female_perticipent', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('po_total_perticipent', models.IntegerField(blank=True, default=0, null=True)),
                ('me_male_perticipent', models.CharField(blank=True, max_length=400, null=True)),
                ('me_female_perticipent', models.CharField(blank=True, max_length=400, null=True)),
                ('me_total_perticipent', models.IntegerField(blank=True, default=0, null=True)),
                ('other_male_perticipent', models.CharField(blank=True, max_length=400, null=True)),
                ('other_female_perticipent', models.CharField(blank=True, max_length=400, null=True)),
                ('other_total_perticipent', models.IntegerField(blank=True, default=0, null=True)),
                ('total_perticipent', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
