# Generated by Django 4.0 on 2022-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_organization_training_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='information_of_facilitator_internal',
            new_name='information_of_facilitator_internal_contact',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='information_of_facilitator_official',
            new_name='information_of_facilitator_internal_designation',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='information_of_facilitator_private',
            new_name='information_of_facilitator_internal_name',
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_internal_organization',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_official_contact',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_official_designation',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_official_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_official_organization',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_private_contact',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_private_designation',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_private_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='information_of_facilitator_private_organization',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
