# Generated by Django 4.0 on 2022-02-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
