# Generated by Django 4.0 on 2022-02-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_training_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
    ]
