# Generated by Django 4.0 on 2022-02-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_training_categorye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='categorye',
        ),
    ]
