# Generated by Django 4.0 on 2022-02-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_training_categorye'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='categorye',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
